deploy:
  provider: heroku
  api_key:
    secure: hBt7bIOsZL2nQm4q2OsJ1ySQxcBCIOV0hugGikpnkma49Pt1mfLDDldRVJqshwisIffRKztRfdvcVRAHbCTfQM4WgSw/N5Sbjhs1b96y7ZtZBJ00/eMLvi+z5fQiGN3msrl1qS/chsdunJEZPq6Le1QdIh7u7DX5UuF60W3SSCgOKPNGwP1UKhjo6NSTjmC++IV7pNBWEMkzan4r9iFcVScOL4m9edqz2/uYh36jJSP3CvblQ40NJ/hIRmEiuaheju1VUfD7agArHOPErlzrTa7sQKct9Ve636J3Q+Giwh92wK2C1lRU0pCzeutqiSBWhryqehS5Shj4uH1us/5Eao3D5BzsWUZsZtzv/HbNPJelwMYBEVvpWQDepMTh8csNev9RBVWqo37Hsst8EQr9z0DyS0PiYaizDYs+xTnzxYMn3ic1EAbl1iUL1kHSBIjUrz8fmg8o6AUj6IaGZKLkluzOQs57+VbU/fXcP4Z10nOoTSpgqA/f2uMAMKvwaq/tjyZeFi5jewOtpYz9Pc4SLzn+sQBVCQwvzdPPPPdBTG6pU7uMlOabXC/FIMkNh1XAuf7Qk6sB6b4cRsYicS0dq60Dtg7LzOgyF3d7XrWVbNLvZTI0cdMMzbLmspSc5gAuPPdUfq/q3MEWL2TYof+Cgl1ZH/pKYUlX5u+qLPIaqFU=
  app: daily-learning
  on:
    repo: JenHsuan/100daysOfCodeIdeas
  skip_cleanup: 'true'
