# Generated by Django 3.0.3 on 2020-05-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0003_auto_20200516_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.IntegerField(choices=[(0, 'devto'), (1, 'medium')], default=0),
        ),
    ]
