# Generated by Django 3.0.3 on 2020-05-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0004_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='decription',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
