# Generated by Django 3.0.3 on 2020-05-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0006_auto_20200516_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(),
        ),
    ]
