# Generated by Django 3.0.3 on 2020-05-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0007_auto_20200516_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateField(),
        ),
    ]
