# Generated by Django 3.0.3 on 2020-06-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0008_auto_20200523_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
    ]
