# Generated by Django 3.0.3 on 2020-06-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0009_auto_20200601_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=64),
        ),
    ]
