# Generated by Django 3.0.3 on 2020-06-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0010_auto_20200606_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hasSubscribed',
            field=models.BooleanField(default=True),
        ),
    ]
