# Generated by Django 3.0.3 on 2020-06-14 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiServer', '0012_auto_20200614_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='reader',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL),
        ),
    ]
