# Generated by Django 3.0.3 on 2020-06-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0015_auto_20200614_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='apiServer.Item'),
        ),
    ]
