# Generated by Django 3.0.3 on 2020-06-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0016_auto_20200614_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarks',
            old_name='items',
            new_name='bookmarks',
        ),
    ]
