# Generated by Django 3.0.3 on 2020-06-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0018_auto_20200614_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='finishedArticles',
            field=models.CharField(default='', max_length=500),
        ),
    ]
