# Generated by Django 3.0.3 on 2020-06-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0019_auto_20200614_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64)),
                ('hasSubscribed', models.BooleanField(default=True)),
                ('provider', models.CharField(default='', max_length=500)),
                ('bookmarks', models.CharField(default='', max_length=500)),
                ('finishedArticles', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='article',
        ),
        migrations.DeleteModel(
            name='Bookmarks',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
