# Generated by Django 3.0.3 on 2020-06-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0020_auto_20200614_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
