# Generated by Django 3.0.3 on 2020-06-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0021_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
